workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "web"

stages:
  - build

lint-markdown:
  stage: build
  image: node:lts
  script:
    - npm install -g markdownlint-cli
    - markdownlint "**/*.md"

lint-yaml:
  stage: build
  image: python:3.13
  script:
    - pip install yamllint
    - yamllint .

build-website:
  stage: build
  image: node:lts
  script:
    - npm install
    - npm run build
