import { themes as prismThemes } from 'prism-react-renderer';
import { NormalizedSidebar, NormalizedSidebarItem } from "@docusaurus/plugin-content-docs/src/sidebars/types.js";
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

function startWithSameWord(a: string, b: string): boolean {
  if (a == null || b == null) {
    return false
  }

  const aFirst = a.split('/').pop()?.split('-')[0].trim();
  const bFirst = b.split('/').pop()?.split('-')[0].trim();
  return aFirst === bFirst;
}

function sortSidebarItems(items: NormalizedSidebar): NormalizedSidebar {
  const sortItems = (items: NormalizedSidebar): NormalizedSidebar => {
    const sortedItems = [...items].sort((a, b) => {
      if (a.type === 'category' || b.type === 'category') {
        return 1
      }

      // remove file extension (otherwise "foo.md" would come after "foo-bar.md")
      const aId = ('id' in a ? a.id : '').replace('.md', '');
      const bId = ('id' in b ? b.id : '').replace('.md', '');

      if (!startWithSameWord(aId, bId)) {
        return 1;
      }

      return aId.localeCompare(bId);
    });

    return sortedItems.map((item: NormalizedSidebarItem) => {
      if (item.type === 'category') {
        return { ...item, items: sortItems(item.items) };
      }
      return item;
    }).filter((item: NormalizedSidebarItem) => {
      return item.type !== 'category' || item.label !== 'archive';
    });
  };

  return sortItems(items);
}

const config: Config = {
  title: 'DevPro Technical Notes',
  tagline: 'Learning can be fun!',
  favicon: 'img/favicon.ico',

  future: {
    v4: true
  },

  url: 'https://tech.devpro.fr',
  baseUrl: '/',
  organizationName: 'devpro',
  projectName: 'tech-notes',
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en']
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          path: 'docs',
          async sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            // fix: DefaultSidebarItemsGenerator compares with file extension so it does an invalid comparison between '.' and '-' (for example put terraform-cli.md before terraform.md)
            // DefaultSidebarItemsGenerator doesn't share the position so we have limited options
            // we'll evaluate the sort only when the file starts with the same word
            // ref. https://docusaurus.io/docs/sidebar/autogenerated#customize-the-sidebar-items-generator
            return sortSidebarItems(sidebarItems);
          }
        },
        theme: {
          customCss: './src/css/custom.css'
        }
      } satisfies Preset.Options
    ]
  ],

  themes: [
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        indexDocs: true,
        indexBlog: false,
        indexPages: false,
        docsRouteBasePath: '/',
        docsDir: 'docs',
        searchBarPosition: 'right',
        searchBarShortcut: true,
        searchBarShortcutHint: true
      }
    ]
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    navbar: {
      title: 'DevPro Tech Notes',
      logo: {
        alt: 'DevPro',
        src: 'img/husky_logo.png'
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'organizationSidebar',
          position: 'left',
          label: 'Organizations'
        },
        {
          type: 'docSidebar',
          sidebarId: 'fundamentalSidebar',
          position: 'left',
          label: 'Fundamentals'
        },
        {
          type: 'docSidebar',
          sidebarId: 'guideSidebar',
          position: 'left',
          label: 'Guides'
        },
        {
          type: 'docSidebar',
          sidebarId: 'studySidebar',
          position: 'left',
          label: 'Studies'
        },
        {
          href: 'https://github.com/devpro/tech-notes',
          label: 'GitHub',
          position: 'right'
        }
      ]
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Organizations',
          items: [
            {
              label: 'Communities',
              to: '/organizations/communities/'
            },
            {
              label: 'Companies',
              to: '/organizations/companies/'
            },
            {
              label: 'Foundations',
              to: '/organizations/foundations/'
            },
            {
              label: 'Independent projects',
              to: '/organizations/independent-projects/'
            },
            {
              label: 'Institutions',
              to: '/organizations/institutions/'
            }
          ]
        },
        {
          title: 'Fundamentals',
          items: [
            {
              label: 'Infrastructure',
              to: '/fundamentals/infrastructure/'
            },
            {
              label: 'Practices',
              to: '/fundamentals/practices/'
            },
            {
              label: 'Solution design',
              to: '/fundamentals/solution-design/'
            },
            {
              label: 'Standards',
              to: '/fundamentals/standards/'
            }
          ]
        },
        {
          title: 'Guides',
          items: [
            {
              label: 'Courses',
              to: '/guides/courses/'
            },
            {
              label: 'Learning paths',
              to: '/guides/learning-paths/'
            },
            {
              label: 'Procedures',
              to: '/guides/procedures/'
            },
            {
              label: 'Workstations',
              to: '/guides/workstations/'
            }
          ]
        },
        {
          title: 'Studies',
          items: [
            {
              label: 'ADRs',
              to: '/studies/adr/'
            }
          ]
        },
        {
          title: 'More',
          items: [
            {
              label: 'DevPro Presentations',
              href: 'https://presentations.devpro.fr'
            },
            {
              label: 'Kubernetes Essentials',
              href: 'https://github.com/devpro/kubernetes-essentials'
            },
            {
              label: 'Kube Workload Toolkit',
              href: 'https://kwt.devpro.fr'
            }
          ]
        }
      ],
      copyright: `Copyright © ${new Date().getFullYear()} DevPro. Built with Docusaurus.`
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'batch', 'csharp', 'ini', 'javascript', 'php', 'powershell', 'ruby', 'sql', 'toml']
    },
  } satisfies Preset.ThemeConfig
};

export default config;
