import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  organizationSidebar: [{type: 'autogenerated', dirName: 'organizations'}],
  fundamentalSidebar: [{type: 'autogenerated', dirName: 'fundamentals'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  studySidebar: [{type: 'autogenerated', dirName: 'studies'}]
};

export default sidebars;
