name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  python_version: "3.10"

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      - name: Lints Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}
      - name: Install Pythons packages
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML files
        run: |
          yamllint .
      - name: Install JavaScript dependencies
        run: npm install
      - name: Build website
        run: npm run build
